# Generated by Django 2.1.5 on 2019-09-29 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField(default=None, null=True)),
                ('algorithm', models.CharField(max_length=300)),
                ('paid', models.FloatField(default=0)),
                ('bought_stocks_value', models.FloatField(default=0)),
                ('gain', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('tmc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('namad', models.CharField(max_length=300)),
                ('avalin', models.CharField(max_length=300)),
                ('payani', models.CharField(max_length=300)),
                ('akharin_moamele', models.CharField(max_length=300)),
                ('tedad_moamelat', models.CharField(max_length=300)),
                ('hajm_moamelat', models.CharField(max_length=300)),
                ('arzesh_moamelat', models.CharField(max_length=300)),
                ('baze_rooz_kam', models.CharField(max_length=300)),
                ('baze_rooz_ziad', models.CharField(max_length=300)),
                ('dirooz', models.CharField(max_length=300)),
                ('eps', models.CharField(max_length=300)),
                ('mojaz_ziad', models.CharField(max_length=300)),
                ('mojaz_kam', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('value', models.FloatField()),
                ('volume', models.FloatField()),
                ('last', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.Stock')),
            ],
        ),
    ]
