# Generated by Django 2.1.5 on 2019-02-02 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=300)),
                ('date', models.FloatField()),
                ('first', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('value', models.FloatField()),
                ('vol', models.FloatField()),
                ('openint', models.FloatField()),
                ('per', models.FloatField()),
                ('open', models.FloatField()),
                ('last', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmc_id', models.CharField(max_length=300)),
                ('q1', models.CharField(max_length=300)),
                ('namad', models.CharField(max_length=300)),
                ('nam', models.CharField(max_length=300)),
                ('q2', models.CharField(max_length=300)),
                ('avalin', models.FloatField()),
                ('payani', models.FloatField()),
                ('akharin_moamele', models.FloatField()),
                ('tedad_moamelat', models.FloatField()),
                ('hajm_moamelat', models.FloatField()),
                ('arzesh_mamelat', models.FloatField()),
                ('baze_rooz_kam', models.FloatField()),
                ('baze_rooz_ziad', models.FloatField()),
                ('dirooz', models.FloatField()),
                ('eps', models.FloatField()),
                ('q3', models.FloatField()),
                ('q4', models.FloatField()),
                ('q5', models.FloatField()),
                ('q6', models.FloatField()),
                ('mojaz_ziad', models.FloatField()),
                ('mojaz_kam', models.FloatField()),
                ('q7', models.FloatField()),
                ('q8', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.Stock'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='bought',
            field=models.ManyToManyField(to='indicator.Stock'),
        ),
    ]
