# Generated by Django 2.1.5 on 2019-09-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='dirooz',
        ),
        migrations.AlterField(
            model_name='stock',
            name='akharin_moamele',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='arzesh_moamelat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='avalin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='baze_rooz_kam',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='baze_rooz_ziad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='eps',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='hajm_moamelat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='mojaz_kam',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='mojaz_ziad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='payani',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tedad_moamelat',
            field=models.FloatField(),
        ),
    ]
