# Generated by Django 2.1.5 on 2019-02-02 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indicator.Stock')),
            ],
        ),
        migrations.AlterField(
            model_name='indicator',
            name='bought',
            field=models.ManyToManyField(to='indicator.Bought_stock'),
        ),
    ]
