# Generated by Django 2.1.5 on 2019-10-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_auto_20190929_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0)),
                ('profit', models.FloatField(default=None, null=True)),
                ('buy_stock_log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buy', to='indicator.StockLog')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indicator.Indicator')),
                ('sell_stock_log', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sell', to='indicator.StockLog')),
            ],
        ),
    ]
