# Generated by Django 2.1.5 on 2019-10-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_tradelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='akharin_moamele',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='arzesh_moamelat',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='avalin',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='baze_rooz_kam',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='baze_rooz_ziad',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='hajm_moamelat',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mojaz_kam',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mojaz_ziad',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='payani',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='tedad_moamelat',
        ),
    ]
