# Generated by Django 2.1.5 on 2019-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20190202_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='q9',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
