# Generated by Django 2.1.5 on 2019-02-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_stock_q9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='q9',
        ),
    ]
