# Generated by Django 2.1.5 on 2019-02-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_remove_stock_q9'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='open',
            new_name='openp',
        ),
    ]
