# Generated by Django 2.1.5 on 2019-02-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_auto_20190202_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='arzesh_mamelat',
            new_name='arzesh_moamelat',
        ),
    ]
