# Generated by Django 2.1.5 on 2019-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_auto_20190204_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='tmc_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
