# Generated by Django 2.1.5 on 2019-02-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0009_auto_20190204_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
