# Generated by Django 2.1.5 on 2019-02-09 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20190205_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='indicator.Stock'),
        ),
    ]
