# Generated by Django 2.1.5 on 2019-02-10 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0012_auto_20190209_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='bought_stock',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bought_stock',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='algotithm',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bought_stock',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.Stock'),
        ),
    ]
