# Generated by Django 2.1.5 on 2019-02-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0013_auto_20190210_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='algotithm',
            new_name='algorithm',
        ),
    ]
