# Generated by Django 2.1.5 on 2019-02-10 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0015_auto_20190210_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
