# Generated by Django 2.1.5 on 2019-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0016_indicator_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
