# Generated by Django 2.1.7 on 2019-03-31 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0017_auto_20190211_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bought_stock',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bought_stock',
            name='time',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AddField(
            model_name='bought_stock',
            name='buy_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bought_stock',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bought_stock',
            name='purchase_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bought_stock',
            name='sell_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bought_stock',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='bought_stocks_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='gain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='trade_log',
            field=models.ManyToManyField(related_name='trade_log', to='indicator.Bought_stock'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='algorithm',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='bought',
            field=models.ManyToManyField(related_name='bought', to='indicator.Bought_stock'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='last_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tmc_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
