# Generated by Django 2.1.7 on 2019-03-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0018_auto_20190331_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bought_stock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='trade_log',
        ),
        migrations.RemoveField(
            model_name='record',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Bought_stock',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
